Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "db/**/*"
    - "test/dummy/bin/**/*"
    - "test/dummy/config/**/*"
    - "test/dummy/db/**/*"

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Exclude:
    - "test/integration/**/*"

Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/NumericPredicate:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Style/VariableNumber:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  SupportedStyles:
    - with_first_parameter
    - with_fixed_indentation
