language: ruby
rvm:
  - 2.2.2
addons:
  code_climate:
    repo_token:
      secure: "HKKbZAmLeXqn/dDc4mmkj1+nxmrlwmp4WwWB1c0ict7445u8tkdF92ffXUmoS/L3Xfou+D95DGRM1MWXhMSFwAg60mpgn20j78uonlo3iiaGWwMI4Ti2juYop0AAyfFpcFimrCSz5HQirY+NFImx8LXvVZqhMTxs9XN5iQ0IWgbyyMkygYgq62P+q5LZrMlpr7K0h3mnPYUCQgNfKQ+cw7uUdMO7bY4YtLYMARV5NmwoTbfC4ZWKemHPJk9LhENz3PQD8vbPOhpv4wRVSZvLTqskCDDfmVFY64fhzrsz5o27WpxKiZTx9Iee0OPTzod7FvMqO0Na6b3g7Mvv8QGzdT9qBZCesa1w0ErKhs5Ny7w5TaDAUUppRRviYCENJrTC+o9QFqodiYa+8xYA6qiTDYBHRE0BLiCbZn1ptgCoZUAnfvhNL45PZmqGIeGhIWfeC5iH+U/ercc2TJ5rVVW0YkDlDAnt4zWgQF5aNshlMBGaTFKBBrBrKmIfQInnW3zugb7HipH8L2gZI/HAbgRf3bDu3sYYCFe+9jrwDzenKbR2SZBKIN2b0xZUptwJCp06uPOVt6Q54TvkQaRfpHIVS9OZpAkOU34JvNlft6/vldxFBWNlfwrKGNSkskTx17PthrUY4VBPY4BIP565zUNXzfOV+iwb27FC1mixAwJzNeI="
script: "bundle exec rake test"
